name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        working-directory: ./paper
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: paper/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex paper/main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: paper/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Store pdf
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf