name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex -draftmode
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape -draftmode
      - name: bibtex
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main
          compiler: bibtex
          args: 
      - name: makeglossaries
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main
          compiler: makeglossaries
          args: 
      - name: pdflatex regenerate
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: out/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode
      - name: pdflatex main
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main.tex
          compiler: pdflatex
          args:
      - name: Store pdf
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: .paper/main.pdf