name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - name: Run - pdflatex -draftmode
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape -draftmode
      - name: Run - bibtex
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main
          compiler: bibtex
          args: 
      - name: Run - makeglossaries
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main
          compiler: makeglossaries
          args: 
      - name: Run - pdflatex regenerate
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Run - pdflatex main
        if: ${{ always() }}
        uses: dante-ev/latex-action@edge
        with:
          working_directory: ./paper
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: List Files
        if: ${{ always() }}
        run: |
          ls -la
          cd ./paper
          ls -la
      - name: Store pdf
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: ./paper/main.pdf
      - name: Release
        if: ${{ always() }}
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.buildnumber.outputs.build_number }}
          tag_name: ${{ github.ref }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{secrets.github_token}}
      - name: Upload Artifact
        if: ${{ always() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.github_token}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paper/main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf